#!/usr/bin/env python3
"""
Wallet Setup Script for Tempo Moderato Testnet

Creates server + client wallets, funds them via the testnet faucet,
and writes credentials to a separate file for the user to copy into .env files.

Usage:
    python scripts/setup_wallets.py              # Generate new wallets
    python scripts/setup_wallets.py --use-existing  # Fund existing wallets from .env files
"""

import argparse
import os
import secrets
import sys
from pathlib import Path

import httpx
from eth_account import Account

RPC_URL = "https://rpc.moderato.tempo.xyz"
CHAIN_ID = 42431
PATHUSD_ADDRESS = "0x20c0000000000000000000000000000000000000"

# ERC-20 balanceOf(address) function selector
BALANCE_OF_SELECTOR = "70a08231"

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CREDS_FILE = PROJECT_ROOT / ".wallet-creds"


def rpc_call(method: str, params: list, url: str = RPC_URL) -> dict:
    """Make a JSON-RPC call and return the result."""
    payload = {"jsonrpc": "2.0", "method": method, "params": params, "id": 1}
    resp = httpx.post(url, json=payload, timeout=30.0)
    resp.raise_for_status()
    data = resp.json()
    if "error" in data:
        raise RuntimeError(f"RPC error: {data['error']}")
    return data.get("result")


def verify_connectivity():
    """Verify RPC endpoint is reachable and returns the expected chain ID."""
    print(f"Connecting to {RPC_URL}...")
    result = rpc_call("eth_chainId", [])
    chain_id = int(result, 16)
    if chain_id != CHAIN_ID:
        print(f"  ERROR: Expected chain ID {CHAIN_ID}, got {chain_id}")
        sys.exit(1)
    print(f"  Chain ID: {chain_id} (0x{chain_id:x}) -- Tempo Moderato confirmed")


def generate_wallet(label: str) -> tuple:
    """Generate a new secp256k1 key pair."""
    account = Account.create()
    private_key = account.key.hex()
    if private_key.startswith("0x"):
        private_key = private_key[2:]
    print(f"  {label} address: {account.address}")
    return private_key, account.address


def fund_wallet(address: str, label: str):
    """Fund a wallet via the Moderato faucet RPC method."""
    print(f"  Funding {label} ({address})...")
    result = rpc_call("tempo_fundAddress", [address])
    print(f"  Faucet response: {result}")


def get_pathusd_balance(address: str) -> int:
    """Query pathUSD balance for an address via eth_call."""
    if address.startswith("0x"):
        address_stripped = address[2:]
    else:
        address_stripped = address
    calldata = "0x" + BALANCE_OF_SELECTOR + address_stripped.lower().zfill(64)
    call_params = {"to": PATHUSD_ADDRESS, "data": calldata}
    result = rpc_call("eth_call", [call_params, "latest"])
    if result and result != "0x":
        return int(result, 16)
    return 0


def write_creds_file(
    server_key: str,
    server_address: str,
    client_key: str,
    client_address: str,
    mpp_secret: str,
):
    """Write generated credentials to .wallet-creds for the user to copy."""
    CREDS_FILE.write_text(
        f"""# Generated wallet credentials -- copy these into your .env files
# Generated by: python scripts/setup_wallets.py

# -- Server (.env) --
TEMPO_SERVER_PRIVATE_KEY={server_key}
# Server address: {server_address}

# -- Client (.env.client) --
TEMPO_CLIENT_PRIVATE_KEY={client_key}
# Client address: {client_address}

# -- MPP secret (.env) --
MPP_SECRET_KEY={mpp_secret}
"""
    )
    print(f"  Wrote credentials to {CREDS_FILE}")


def load_existing_keys() -> tuple:
    """Load existing private keys from .env files."""
    from dotenv import dotenv_values

    server_env = dotenv_values(PROJECT_ROOT / ".env")
    client_env = dotenv_values(PROJECT_ROOT / ".env.client")

    server_key = server_env.get("TEMPO_SERVER_PRIVATE_KEY", "")
    client_key = client_env.get("TEMPO_CLIENT_PRIVATE_KEY", "")

    if not server_key or server_key == "your_server_private_key_hex":
        print("ERROR: No valid TEMPO_SERVER_PRIVATE_KEY found in .env")
        sys.exit(1)
    if not client_key or client_key == "your_client_private_key_hex":
        print("ERROR: No valid TEMPO_CLIENT_PRIVATE_KEY found in .env.client")
        sys.exit(1)

    return server_key, client_key


def main():
    parser = argparse.ArgumentParser(
        description="Set up Tempo Moderato testnet wallets for video-gen-mpp"
    )
    parser.add_argument(
        "--use-existing",
        action="store_true",
        help="Fund existing wallets from .env files instead of generating new ones",
    )
    args = parser.parse_args()

    print()
    print("=" * 60)
    print("Tempo Moderato Testnet Wallet Setup")
    print("=" * 60)
    print()

    # Step 1: Verify RPC connectivity
    verify_connectivity()
    print()

    # Step 2: Get or generate keys
    if args.use_existing:
        print("Loading existing wallets from .env files...")
        server_key, client_key = load_existing_keys()
        if server_key.startswith("0x"):
            server_key = server_key[2:]
        if client_key.startswith("0x"):
            client_key = client_key[2:]
        server_account = Account.from_key("0x" + server_key)
        client_account = Account.from_key("0x" + client_key)
        server_address = server_account.address
        client_address = client_account.address
        print(f"  Server address: {server_address}")
        print(f"  Client address: {client_address}")
    else:
        print("Generating new wallets...")
        server_key, server_address = generate_wallet("Server")
        client_key, client_address = generate_wallet("Client")

    print()

    # Step 3: Fund wallets via faucet
    print("Funding wallets via tempo_fundAddress...")
    fund_wallet(server_address, "server")
    fund_wallet(client_address, "client")
    print()

    # Wait for faucet transactions to be mined
    import time
    print("Waiting for faucet transactions to confirm...")
    time.sleep(3)

    # Step 4: Verify pathUSD balances
    print("Verifying pathUSD balances...")
    server_balance = get_pathusd_balance(server_address)
    client_balance = get_pathusd_balance(client_address)
    # pathUSD has 6 decimals
    print(f"  Server pathUSD: {server_balance / 1_000_000:,.2f}")
    print(f"  Client pathUSD: {client_balance / 1_000_000:,.2f}")
    print()

    # Step 5: Write creds file (only for new wallets)
    if not args.use_existing:
        print("Writing credentials file...")
        mpp_secret = secrets.token_hex(32)
        write_creds_file(server_key, server_address, client_key, client_address, mpp_secret)
        print()

    # Summary
    print("=" * 60)
    print("Setup Complete")
    print("=" * 60)
    print()
    print(f"  Server: {server_address}")
    print(f"  Client: {client_address}")
    print(f"  Server pathUSD: {server_balance / 1_000_000:,.2f}")
    print(f"  Client pathUSD: {client_balance / 1_000_000:,.2f}")
    print()
    print(f"  Explorer: https://explore.tempo.xyz/address/{server_address}")
    print(f"  Explorer: https://explore.tempo.xyz/address/{client_address}")
    print()
    if not args.use_existing:
        print("Next steps:")
        print(f"  1. Copy keys from {CREDS_FILE} into your .env and .env.client files")
        print("  2. Edit .env and set your FAL_AI_KEY (if not already set)")
        print("  3. Start the server: python main.py")
        print("  4. Run the client:   python client-pay.py --prompt 'test' --duration 5")
    print()


if __name__ == "__main__":
    main()
